# Forward 5252 to 5252
FROM ubuntu:latest

WORKDIR /app

RUN apt-get update && \
    apt-get upgrade -y

RUN apt-get install -y python3 python3-pip

RUN rm /usr/lib/python*/EXTERNALLY-MANAGED

RUN pip3 install flask

COPY ./api.py .

EXPOSE 5252

ENTRYPOINT [ "python3", "api.py" ]
